name: Update SGModules

on:
  schedule:
    - cron: '0 0 * * *'  # Run once a day at midnight UTC
  workflow_dispatch:

jobs:
  update_sgmodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install curl

    - name: Fetch and modify SGModule files
      run: |
        urls=(
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Zhihu_remove_ads.plugin'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Weixin_Official_Accounts_remove_ads.plugin'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Weixin_external_links_unlock.plugin'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Weibo_remove_ads.plugin'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/UnionPay_remove_ads.plugin'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Remove_splash_screen_ads.plugin'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/JD_Price.plugin'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Cainiao_remove_ads.plugin'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Bilibili_remove_ads.plugin'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Amap_remove_ads.plugin'
        )
        for url in "${urls[@]}"; do
          content=$(curl -sSL "$url")
          modified_content=$(echo "$content" | \
            sed -e 's/^\(reject\|REJECT\)/REJECT-TINYGIF/g' \
                -e 's/^\(hostname =\)/hostname = %APPEND%/g' \
                -e 's/^\(tag =\)//g')
          filename=$(basename "$url" | sed 's/\.plugin$/.sgmodule/')
          if [[ ! -f "$filename" ]]; then
            echo "$modified_content" > "$filename"
            git add "$filename"
            git commit -m "Add $filename"
          fi
        done

    - name: Apply regex replacements
      run: |
        find . -type f -name '*.sgmodule' -exec sed -i 's/^\(reject\|REJECT\)/REJECT-TINYGIF/g' {} +
        find . -type f -name '*.sgmodule' -exec sed -i 's/^\(hostname =\)/hostname = %APPEND%/g' {} +
        find . -type f -name '*.sgmodule' -exec sed -i 's/^\(tag =\)/tag =/g' {} +

    - name: Commit and push changes
      run: |
        git config --global user.email "tk4900@gmail.com"
        git config --global user.name "warecast"
        git add .
        git commit -m "Update files"
        git push