name: Modify files using regex

on:
  push:
    branches:
      - main

jobs:
  modify_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Modify and commit files
        run: |
          # Define the list of URLs and their corresponding file names
          urls=(
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Zhihu_remove_ads.plugin,Zhihu_remove_ads.sgmodule'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Weixin_Official_Accounts_remove_ads.plugin,Weixin_Official_Accounts_remove_ads.sgmodule'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Weixin_external_links_unlock.plugin,Weixin_external_links_unlock.sgmodule'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Weibo_remove_ads.plugin,Weibo_remove_ads.sgmodule'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/UnionPay_remove_ads.plugin,UnionPay_remove_ads.sgmodule'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Remove_splash_screen_ads.plugin,Remove_splash_screen_ads.sgmodule'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/JD_Price.plugin,JD_Price.sgmodule'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Cainiao_remove_ads.plugin,Cainiao_remove_ads.sgmodule'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Bilibili_remove_ads.plugin,Bilibili_remove_ads.sgmodule'
            'https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Amap_remove_ads.plugin,Amap_remove_ads.sgmodule'
          )
          # Loop over the URLs and their file names
          for url in "${urls[@]}"; do
            # Split the URL and file name using a comma
            IFS=',' read -r url file_name <<< "$url"
            # Fetch the content from the URL
            content=$(curl -s "$url")
            # Modify the content using regex
            modified=$(echo "$content" | sed -e 's/^\(reject\|REJECT\)/REJECT-TINYGIF/g' \
                                                 -e 's/^\(hostname =\)/hostname = %APPEND%/g' \
                                                 -e '/^tag =/d')
            # Save the modified content to a new file with the specified file name
            echo "$modified" > "$file_name"
            # Encode the modified content as base64
            encoded=$(base64 "$file_name" | tr -d '\n')
            # Get the current commit SHA
            sha=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                  "https://api.github.com/repos/${{ github.repository }}/branches/main" \
                  | jq -r '.commit.sha')
            # Get the tree SHA for the current commit
            tree=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                   "https://api.github.com/repos/${{ github.repository }}/git/commits/$sha" \
                   | jq -r '.tree.sha')
            # Create a new blob object with the modified content
            blob=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                   -d "{\"content\":\"$encoded\",\"encoding\":\"base64\"}" \
                   "https://api.github.com/repos/${{ github.repository }}/git/blobs" \
                   | jq -r '.sha')
            # Create a new tree object with the modified file name and blob SHA
            tree=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                   -d "{\"base_tree\":\"$tree\",\"tree\":[{\"path\":\"$file_name\",\"mode\":\"100644\",\"type\":\"blob\",\"sha\":\"$blob\"}]}" \
                   "https://api.github.com/repos/${{ github.repository }}/git/trees" \
                   | jq -r '.sha')
            # Create a new commit with the modified file and updated tree SHA
            curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"message\":\"Modify file\",\"parents\":[\"$sha\"],\"tree\":\"$tree\"}" \
            "https://api.github.com/repos/${{ github.repository }}/git/commits\""