name: Replace contents
on:
  push:
    branches: [ main ]

jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Replace strings
      run: |
        mkdir -p Surge
        for file in Loon/*.plugin; do
          cat $file | \
          sed -E 's/(^|\W)(reject|REJECT)\b/\1REJECT-TINYGIF/g; s/hostname =/hostname = %APPEND%/g; s/^tag =.*$/tag =/g' \
          > Surge/$(basename $file .plugin).sgmodule
        done

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add Surge
        git commit -m "Replace strings in Loon plugins"
        git push
