name: Process Files

on:
  push:
    branches: [main]

jobs:
  process-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Process files
      run: |
        # Read all file contents from Loon directory
        files=$(find ./Loon -type f)
        for file in $files
        do
          # Use regex to process the contents
          modified_contents=$(sed -e 's/reject-.*$/REJECT-TINYGIF/gI' -e 's/REJECT-.*$/REJECT-TINYGIF/gI' -e 's/hostname =/hostname = %APPEND%/g' $file)

          # Save modified contents to Surge directory and change file extension
          surge_dir=./Surge
          surge_file=$(basename $file .plugin).sgmodule
          surge_path=$surge_dir/$surge_file
          mkdir -p $surge_dir
          echo "$modified_contents" > $surge_path
        done

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Process contents from plugin and save to sgmodule"
