name: Modify contents

on:
  push:
    branches:
      - main

jobs:
  modify-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Modify files
        run: |
          mkdir -p Surge
          for file in Loon/*.plugin; do
            filename=$(basename "$file")
            sed -e 's/^reject/REJECT-TINYGIF/g' -e 's/^REJECT/REJECT-TINYGIF/g' -e 's/hostname =/hostname = %APPEND%/g' -e '/^tag = /d' "$file" > "Surge/${filename%.*}.sgmodule"
          done

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: modify strings and save to sgmodule
          commit_options: '--no-verify'
